### ISSUE TITLE
Not seems to work

### ISSUE THREAD

**Issue by Davinel17** [TGRHavoc/live_map#96] opened 2023-01-22 04:39 UTC
I install the live_map

i suceed to add manually blips butnothing work for the players 
"livemap:internal_AddPlayerData" seems to not existing anymore.
Is the ressource still working ? 
Is working with linux server ? 

Any help ?

Thank you

**Comment by TGRHavoc** [comment] 2024-02-21 19:22
Closing as duplicate of #71.

**Closed as not planned by TGRHavoc** 2024-02-21 19:22 UTC
Labels: question
